### ISSUE TITLE
Quality of final Video and Error in CLI

### ISSUE THREAD

**Issue by Mauzifus** [Clemens-E/licpl-censor#1]
Hi, 
I've tested your great licpl-censor and have some feedback for you.
Firstly, the output bitrate is very low - for a 2k input, I got a video with about an 8k bitrate, from an input of 16k - a lot of quality is lost here. It would be nice if this could be adjusted.

Secondly, I could only test everything with the Windows version, specifically through the GUI.
I encountered an error message with both the Windows-CLI and the Python-CLI.
Started with:
licpl-censor-0.0.2-CLI.exe --input Drive\Folder\INPUT --frame-memory 5 --batch 4 --model Drive\Folder\0.0.1.pt --threads 2 --save-training Drive\FolderTraining --output Drive\Folder\OUTPUT

Error message:
using cuda for detection
found 51 video files
reading video Videopfad.avi
Traceback (most recent call last):
File "cli.py", line 63, in <module>
File "video_processing.py", line 75, in readVideoGetDetections
TypeError: 'module' object is not callable
[18748] Failed to execute script 'cli' due to unhandled exception!

Additionally, this error message also appears with mp4 and mov files.
Greetings
Mauzifus

**Comment by Clemens-E** [comment]
Hi, thanks for providing feedback.
Since my main goal is to make the best model I can with what I have (and can afford), I have to admit that the censoring is not perfect (yet).

The part in the CLI that is causing the issue will be resolved today or tomorrow. I already found the issue, was an oversight on my end.

I will check how I can fix the bitrate problem because the output bitrate is not adjusted or lowered intentionally.

**Comment by Clemens-E** [comment]
added `--quality` option and increased the default to 6, and fixed the cli version
